Update CMakeLists.txt
Link to libstdc++ for linux.
This appears to be required for gcc < 9
Else linker errors "like undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'"
Might be CentOS only or GCC <9 only so require a version check